global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'apache'
    metrics_path: '/server-status'
    params:
      auto: ['json']
    static_configs:
      - targets: ['web:80']