server:
  http_listen_port: 9080

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: apache
      __path__: /var/log/apache2/*log

- job_name: application
  static_configs:
  - targets:
      - localhost
    labels:
      job: application
      __path__: /var/www/html/logs/*log