name: Deploy to Rocky Linux on GCP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH Key
      run: |
        echo "${{ secrets.GCP_SSH_KEY }}" > rocky-key
        chmod 600 rocky-key

    - name: Clone from Afri Github
      run: |
        ssh -i rocky-key -o StrictHostKeyChecking=no \
          ${{ secrets.GCP_USER }}@${{ secrets.GCP_HOST }} \
          "rm -rf restaurantdb/ && \
          git clone https://github.com/afriyanto1/restaurantdb.git && \
          ls -la"

    - name: Deploy Application
      run: |
        ssh -i rocky-key -o StrictHostKeyChecking=no \
          ${{ secrets.GCP_USER }}@${{ secrets.GCP_HOST }} \
          "sudo usermod -aG docker ${{ secrets.GCP_USER }} && \
           cd /restaurantdb/ && \
           docker-compose down && \
           docker-compose up -d --build"

    - name: Verify Deployment
      run: |
        ssh -i rocky-key -o StrictHostKeyChecking=no \
          ${{ secrets.GCP_USER }}@${{ secrets.GCP_HOST }} \
          "docker ps && curl -I http://localhost:8080"