name: Deploy to Rocky Linux on GCP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH Key
      run: |
        echo "${{ secrets.GCP_SSH_KEY }}" > rocky-key
        chmod 600 rocky-key

    - name: Clone from Afri Github
      run: |
        ssh -i rocky-key -o StrictHostKeyChecking=no \
          ${{ secrets.GCP_USER }}@${{ secrets.GCP_HOST }} \
          "rm -rf restaurantdb/ && \
          git clone https://github.com/afriyanto1/restaurantdb.git"

    - name: Deploy Application
      run: |
        ssh -i rocky-key -o StrictHostKeyChecking=no \
          ${{ secrets.GCP_USER }}@${{ secrets.GCP_HOST }} \
          "sudo usermod -aG docker ${{ secrets.GCP_USER }} && \
           cd restaurantdb/ && \
           docker-compose down && \
           docker-compose up -d --build && \
           sleep 60 && \
           docker exec -it mysql8_container chmod 644 /docker-entrypoint-initdb.d/init.sql && \
           docker exec -it mysql8_container mysql -u root -p${{ secrets.MYSQL_PASSWORD }} restaurantdb -e 'source /docker-entrypoint-initdb.d/init.sql'"

    - name: Verify Deployment
      run: |
        ssh -i rocky-key -o StrictHostKeyChecking=no \
          ${{ secrets.GCP_USER }}@${{ secrets.GCP_HOST }} \
          "docker ps && curl --head http://localhost:8080/customerSide/home/home.php"